/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DangNhap;
import DanhSachTaiSan.DBEngine;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author trang
 */
public class DangKy extends javax.swing.JFrame {
    ArrayList<TaiKhoan> dsTK = new ArrayList<>();
    TaiKhoan tk = new TaiKhoan();
    DBEngine db = new DBEngine();
    String fname = "dsTK.dat";
    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
        readData();
        setLocationRelativeTo(null);
        setTitle("Đăng ký");
    }
    
    public void reset(){
        jTextDN.setText("");
        jPassMK.setText("");
    }
    
    public void readData(){
        try {
            dsTK=(ArrayList<TaiKhoan>) db.docFile(fname);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sách hiện tại rỗng!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi đọc dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveData(){
        try {            
            db.LuuFile(fname, dsTK);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi lưu dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDN = new javax.swing.JLabel();
        jLabelMK = new javax.swing.JLabel();
        jTextDN = new javax.swing.JTextField();
        jButtonDangKy = new javax.swing.JButton();
        jPassMK = new javax.swing.JPasswordField();
        jLabelTitl = new javax.swing.JLabel();
        jButtonDangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDN.setText("Tên đăng nhập:");
        jPanel1.add(jLabelDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabelMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMK.setText("Mật khẩu:");
        jPanel1.add(jLabelMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        jPanel1.add(jTextDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        jButtonDangKy.setText("Đăng ký");
        jButtonDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangKyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, -1));
        jPanel1.add(jPassMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, -1));

        jLabelTitl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitl.setText("ĐĂNG KÝ");
        jPanel1.add(jLabelTitl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 100, 40));

        jButtonDangNhap.setText("Đăng nhập");
        jButtonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 480, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangKyActionPerformed
        // TODO add your handling code here:
        String dn = jTextDN.getText();
        String mk = jPassMK.getText();
        tk = new TaiKhoan(dn,mk);
        if(dn.trim().length() == 0 || mk.trim().length() == 0) 
            JOptionPane.showMessageDialog(this,"Phải nhập đầy đủ thông tin!","Thông báo", JOptionPane.WARNING_MESSAGE);
        else if(checkTK(dn)) 
            JOptionPane.showMessageDialog(this,"Đã tồn tại tên đăng nhập!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
        else{
            dsTK.add(tk);
            reset();
            saveData();
            JOptionPane.showMessageDialog(this,"Đã đăng ký tài khoản cho "+dn+"!", "Thông báo", JOptionPane.PLAIN_MESSAGE);
            DangNhap DN = new DangNhap();
                  DN.setVisible(true);
                  setVisible(false);
                  this.dispose();
                  
        }    
         
    }//GEN-LAST:event_jButtonDangKyActionPerformed

    private void jButtonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangNhapActionPerformed
        // TODO add your handling code here:
        DangNhap DN = new DangNhap();
                  setVisible(false);
                  DN.setVisible(true);
                  this.dispose();
    }//GEN-LAST:event_jButtonDangNhapActionPerformed

    public boolean checkTK(String tendk){
        for(TaiKhoan itm : dsTK)
            if(itm.getTenDN().equals(tendk)) return true;
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDangKy;
    private javax.swing.JButton jButtonDangNhap;
    private javax.swing.JLabel jLabelDN;
    private javax.swing.JLabel jLabelMK;
    private javax.swing.JLabel jLabelTitl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassMK;
    private javax.swing.JTextField jTextDN;
    // End of variables declaration//GEN-END:variables
}
