/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MuaSam;

import DangNhap.DangNhap;
import DanhSachTaiSan.JQLTaiSan;
import SuaChua.JQLSuaChua;
import ThanhLy.JTLTaiSan;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Trọng
 */
public class JMSThietBi extends javax.swing.JFrame {
    ArrayList<ThietBi> dsThietBi = new ArrayList<>();
    ArrayList<ThietBi> dsTBWork = new ArrayList<>();
    int dongchon = -1;
    ThietBi tbi = new ThietBi();
    DBEngine db = new DBEngine();
    String fname = "dsMS.dat";
    /**
     * Creates new form JMSThietBi
     */
    public JMSThietBi() {
        initComponents();
        myInt();
        setLocationRelativeTo(null);
        setTitle("Quản lý mua sắm tài sản");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboDM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTenTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSLKho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSLDeNghi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDVTinh = new javax.swing.JTextField();
        BtnThem = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        BtnIn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboDMLoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTB = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nhập")));
        jNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Danh Mục:");
        jNhap.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jComboDM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboDM.setMaximumSize(new java.awt.Dimension(146, 30));
        jComboDM.setMinimumSize(new java.awt.Dimension(146, 30));
        jComboDM.setPreferredSize(new java.awt.Dimension(146, 30));
        jNhap.add(jComboDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 27, 170, -1));

        jLabel3.setText("Tên Tài Sản:");
        jNhap.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jTenTB.setMinimumSize(new java.awt.Dimension(144, 30));
        jTenTB.setPreferredSize(new java.awt.Dimension(144, 30));
        jNhap.add(jTenTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 68, -1, -1));

        jLabel4.setText("Số Lượng Kho:");
        jNhap.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 76, -1, -1));

        jSLKho.setText("0");
        jSLKho.setMinimumSize(new java.awt.Dimension(144, 25));
        jSLKho.setPreferredSize(new java.awt.Dimension(144, 30));
        jNhap.add(jSLKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel5.setText("Số Lượng Đề Nghị:");
        jNhap.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jSLDeNghi.setText("0");
        jSLDeNghi.setMinimumSize(new java.awt.Dimension(144, 25));
        jSLDeNghi.setPreferredSize(new java.awt.Dimension(144, 30));
        jNhap.add(jSLDeNghi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel6.setText("Đơn Vị Tính:");
        jNhap.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jDVTinh.setMinimumSize(new java.awt.Dimension(144, 25));
        jDVTinh.setPreferredSize(new java.awt.Dimension(144, 30));
        jNhap.add(jDVTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        BtnThem.setText("Thêm");
        BtnThem.setMaximumSize(new java.awt.Dimension(70, 30));
        BtnThem.setMinimumSize(new java.awt.Dimension(70, 30));
        BtnThem.setPreferredSize(new java.awt.Dimension(70, 25));
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });
        jNhap.add(BtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 30));

        BtnSua.setText("Sửa");
        BtnSua.setMaximumSize(new java.awt.Dimension(70, 30));
        BtnSua.setMinimumSize(new java.awt.Dimension(70, 30));
        BtnSua.setPreferredSize(new java.awt.Dimension(70, 30));
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });
        jNhap.add(BtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        BtnXoa.setText("Xoá");
        BtnXoa.setMaximumSize(new java.awt.Dimension(70, 30));
        BtnXoa.setMinimumSize(new java.awt.Dimension(70, 30));
        BtnXoa.setPreferredSize(new java.awt.Dimension(70, 30));
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });
        jNhap.add(BtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        BtnIn.setText("In phiếu");
        BtnIn.setMaximumSize(new java.awt.Dimension(70, 30));
        BtnIn.setMinimumSize(new java.awt.Dimension(70, 30));
        BtnIn.setPreferredSize(new java.awt.Dimension(70, 30));
        BtnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInActionPerformed(evt);
            }
        });
        jNhap.add(BtnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 82, -1));

        getContentPane().add(jNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 600, 192));
        jNhap.getAccessibleContext().setAccessibleName("Nhập");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Lọc"));
        jPanel2.setPreferredSize(new java.awt.Dimension(204, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Danh Mục:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 27, -1, -1));

        jComboDMLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboDMLoc.setMinimumSize(new java.awt.Dimension(146, 30));
        jComboDMLoc.setPreferredSize(new java.awt.Dimension(146, 30));
        jComboDMLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDMLocActionPerformed(evt);
            }
        });
        jPanel2.add(jComboDMLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 59, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 11, -1, 190));

        TableTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableTB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 812, 230));

        jMenu1.setText("Đăng xuất");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Chức năng");

        jMenuItem1.setText("Danh sách tài sản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("Sửa chữa tài sản");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Thanh lý tài sản");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed
        // TODO add your handling code here:
        
        if(jTenTB.getText().trim().length()==0)
                JOptionPane.showMessageDialog(null, "Tên tài sản không được để trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else {
            tbi = new ThietBi(jTenTB.getText(),Integer.parseInt(jSLKho.getText()),Integer.parseInt(jSLDeNghi.getText()),jDVTinh.getText(),jComboDM.getSelectedItem().toString());
            if(dsThietBi.contains(tbi))
                JOptionPane.showMessageDialog(null, "Tài sản đã có trong danh sách mua sắm!\n","Lỗi", JOptionPane.ERROR_MESSAGE);
            else{
                dsThietBi.add(tbi);
                LoadTableTB(dsThietBi);
                resetTxt();
                saveData();
            }
        }
    }//GEN-LAST:event_BtnThemActionPerformed

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed
        // TODO add your handling code here:
        if(dongchon != -1){
            dongchon = TableTB.getSelectedRow();            
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){                
                tbi = dsTBWork.get(dongchon);
                tbi = dsThietBi.get(dsThietBi.indexOf(tbi));
                tbi.setTenTB(jTenTB.getText());
                tbi.setsLKho(Integer.parseInt(jSLKho.getText()));
                tbi.setsLDeNghi(Integer.parseInt(jSLDeNghi.getText()));
                tbi.setDvTinh(jDVTinh.getText());
                tbi.setDanhMuc(jComboDM.getSelectedItem().toString());
                LoadTableTB(dsThietBi);
                resetTxt();
                saveData();
            }
        }else
                JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    
    }//GEN-LAST:event_BtnSuaActionPerformed

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
        if (dongchon != -1){
            dongchon = TableTB.getSelectedRow();
            tbi = dsTBWork.get(dongchon);
            tbi = dsThietBi.get(dsThietBi.indexOf(tbi));
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                try {
                    dsThietBi.remove(tbi);
                    LoadTableTB(dsThietBi);
                    resetTxt();
                    saveData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            } 
        }else 
            JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    
    }//GEN-LAST:event_BtnXoaActionPerformed

    private void TableTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTBMouseClicked
        // TODO add your handling code here:
        dongchon = TableTB.getSelectedRow();
        if(dongchon !=-1){
            tbi = dsTBWork.get(dongchon);
            jTenTB.setText(tbi.getTenTB()+"");
            jSLKho.setText(tbi.getsLKho()+"");
            jSLDeNghi.setText(tbi.getsLDeNghi()+"");
            jDVTinh.setText(tbi.getDvTinh()+"");
            jComboDM.setSelectedItem(tbi.getDanhMuc());
        }
    }//GEN-LAST:event_TableTBMouseClicked

    private void BtnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInActionPerformed
        // TODO add your handling code here:
        JMSThietBi_Phieu mSTBForm = new JMSThietBi_Phieu();
        mSTBForm.setVisible(true);
    }//GEN-LAST:event_BtnInActionPerformed

    private void jComboDMLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDMLocActionPerformed
        // TODO add your handling code here:
        ArrayList<ThietBi> dsLoc = new ArrayList<>();
        String itemLoc = jComboDMLoc.getSelectedItem().toString();
        if(itemLoc.equalsIgnoreCase("Tất cả")){
            LoadTableTB(dsThietBi);
            dsTBWork=dsThietBi;
        }            
        else{
            for(ThietBi itm : dsThietBi) 
                if(itm.getDanhMuc().equalsIgnoreCase(itemLoc)) dsLoc.add(itm);
            LoadTableTB(dsLoc);
            dsTBWork=dsLoc;
        }
    }//GEN-LAST:event_jComboDMLocActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        DangNhap dnForm = new DangNhap();
        dnForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JQLTaiSan qlTSForm = new JQLTaiSan();
        qlTSForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JQLSuaChua qlSCForm = new JQLSuaChua();
        qlSCForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JTLTaiSan qlTLForm = new JTLTaiSan();
        qlTLForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMSThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMSThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMSThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMSThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JMSThietBi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIn;
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JTable TableTB;
    private javax.swing.JComboBox<String> jComboDM;
    private javax.swing.JComboBox<String> jComboDMLoc;
    private javax.swing.JTextField jDVTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jNhap;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jSLDeNghi;
    private javax.swing.JTextField jSLKho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTenTB;
    // End of variables declaration//GEN-END:variables

    private void myInt() {
        //Đọc dữ liệu từ file khi khởi động
        readData();
        LoadTableTB(dsThietBi);
        //Tạo combo danh mục
        String dm[]={"Công trình xây dựng","Xe ô tô","Máy móc, thiết bị","Phần mềm ứng dụng","Khác"};
        
        jComboDM.setModel(new javax.swing.DefaultComboBoxModel(dm));
        //Tạo combo danh mục để lọc
        jComboDMLoc.setModel(new javax.swing.DefaultComboBoxModel(dm));
        jComboDMLoc.addItem("Tất cả");
        jComboDMLoc.setSelectedItem("Tất cả");
    }

    private void readData() {
        try {
            dsThietBi = (ArrayList<ThietBi>) db.docFile(fname);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sách hiện tại rỗng!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi đọc dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LoadTableTB(ArrayList<ThietBi> dsThietBi) {
        TableTB.setModel(new TableThietBi(dsThietBi));
    }
    private void resetTxt() {
        jTenTB.setText("");
        jSLKho.setText("0");
        jSLDeNghi.setText("0");
        jDVTinh.setText("");
        jComboDM.setSelectedIndex(0);
    }

    private void saveData() {
        try {
            db.LuuFile(fname,dsThietBi);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi lưu dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
}
