/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuaChua;
import DangNhap.DangNhap;
import DanhSachTaiSan.JQLTaiSan;
import MuaSam.JMSThietBi;
import ThanhLy.JTLTaiSan;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author tú
 */
public class JQLSuaChua extends javax.swing.JFrame {
    ArrayList<SuaChua> dsTTinh = new ArrayList<>();
    ArrayList<SuaChua> dsSCWork = new ArrayList<>();
    int dongchon = -1;
    SuaChua ttinh = new SuaChua();
    SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy");
    DBEngine scc = new DBEngine();
    String fname = "dsSC.dat";

    /**
     * Creates new form JQLSuaChua
     */
    public JQLSuaChua() {
        initComponents();
        myInit();
        setLocationRelativeTo(null);
        setTitle("Quản lý sửa chữa tài sản");
    }
    public void myInit(){
        //Đọc dữ liệu từ file khi khởi động
        readData();
        LoadTableSC(dsTTinh);
        dsSCWork = dsTTinh;
        //Tạo combo danh mục
        String tt[]={"Chờ duyệt","Không duyệt","Được duyệt"};
        jComboTT.setModel(new javax.swing.DefaultComboBoxModel(tt));
        //loc
        jComboTTLoc.setModel(new javax.swing.DefaultComboBoxModel(tt));
        jComboTTLoc.addItem("Tất cả");
        jComboTTLoc.setSelectedItem("Tất cả");
    }
    public void LoadTableSC(ArrayList<SuaChua> ds){
        ttinhCSVC.setModel(new TableSuaChua(ds));
    }
    public void saveData(){        
        try {
            scc.LuuFile(fname,dsTTinh);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi lưu dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void readData(){
        try {
            dsTTinh = (ArrayList<SuaChua>) scc.docFile(fname);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sách hiện tại rỗng!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi đọc dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMaSC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jNguoiBT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDvTinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMaTS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCBKiemTra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jNgaySC = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jNoiDung = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboTT = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextYKien = new javax.swing.JTextArea();
        jButtonXN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttinhCSVC = new javax.swing.JTable();
        jComboTTLoc = new javax.swing.JComboBox<>();
        jButtonInDS = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thực hiện"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã sửa chữa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jMaSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, -1));

        jLabel2.setText("CB bảo trì");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel1.add(jNguoiBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));

        jLabel3.setText("Đơn vị");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 45, -1));
        jPanel1.add(jDvTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        jLabel4.setText("Tài sản SC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(jMaTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        jLabel5.setText("Nội dung");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel6.setText("CB kiểm tra");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        jPanel1.add(jCBKiemTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 170, -1));

        jLabel7.setText("Ngày đem sửa");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jNgaySC.setText("20/5/2023");
        jNgaySC.setToolTipText("Nhập định dạng ngày/tháng/năm");
        jPanel1.add(jNgaySC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 170, -1));

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 73, -1));

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 73, -1));

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 73, -1));

        jNoiDung.setColumns(20);
        jNoiDung.setRows(5);
        jPanel1.add(jNoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 190));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Xét duyệt"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Trạng thái");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jComboTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 116, -1));

        jLabel8.setText("Ý kiến");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextYKien.setColumns(20);
        jTextYKien.setRows(5);
        jPanel2.add(jTextYKien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jButtonXN.setText("Xác nhận");
        jButtonXN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXNActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonXN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 210, 190));

        ttinhCSVC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttinhCSVC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttinhCSVCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttinhCSVC);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 850, 260));

        jComboTTLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboTTLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTTLocActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTTLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, -1));

        jButtonInDS.setText("Xuất DS được duyệt");
        jButtonInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInDSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        jMenu1.setText("Đăng xuất");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Chức năng");

        jMenuItem1.setText("Mua sắm tài sản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Danh sách tài sản");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem4.setText("Thanh lý tài sản");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:        
        if(jMaSC.getText().trim().length()==0||
           jMaTS.getText().trim().length()==0)
                JOptionPane.showMessageDialog(null, "Mã sửa chữa và Tài sản sửa chữa không được bỏ trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else {
            try {
                // Khoi tao mot ,,, moi lay thong tin tu cac control tren man hinh
                ttinh = new SuaChua(jMaSC.getText(),jNguoiBT.getText(),jDvTinh.getText(),jMaTS.getText(),
                                      jNoiDung.getText(),jCBKiemTra.getText(),format.parse(jNgaySC.getText()),
                                      "Chờ duyệt");            
                if(dsTTinh.contains(ttinh)) 
                    JOptionPane.showMessageDialog(null, "Đã tồn tại mã sửa chữa, vui lòng  nhập lại!\n","Lỗi", JOptionPane.ERROR_MESSAGE);
                else{
                    // thuc hien them vao danh sach
                    dsTTinh.add(ttinh);
                    //load lai bang sau khi them va luu thong tin vao file
                    LoadTableSC(dsTTinh);                
                    resetTxt();
                    saveData();
                }            
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Hãy kiểm tra dữ liệu, định dạng ngày kiểu MM/dd/yyyy!\n" + ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        if(dongchon != -1){
            dongchon = ttinhCSVC.getSelectedRow();            
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                try {                    
                    ttinh = dsSCWork.get(dongchon);
                    ttinh = dsTTinh.get(dsTTinh.indexOf(ttinh));
                    ttinh.setMaSC(jMaSC.getText());
                    ttinh.setNguoiBT(jNguoiBT.getText());
                    ttinh.setDvTinh(jDvTinh.getText());
                    ttinh.setMaTS(jMaTS.getText());                   
                    ttinh.setCBKiemTra(jCBKiemTra.getText());
                    ttinh.setNoiDung(jNoiDung.getText());
                    ttinh.setNgaySC(format.parse(jNgaySC.getText()));
                    ttinh.setyKien(jComboTT.getSelectedItem().toString());                    
                    LoadTableSC(dsTTinh);
                    resetTxt();
                    saveData();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Hãy kiểm tra dữ liệu, định dạng ngày kiểu MM/dd/yyyy!\n" + ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else
                JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);                
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        if (dongchon != -1){
            dongchon = ttinhCSVC.getSelectedRow();
            ttinh = dsSCWork.get(dongchon);
            ttinh = dsTTinh.get(dsTTinh.indexOf(ttinh));
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                try {
                    dsTTinh.remove(ttinh);
                    LoadTableSC(dsTTinh);
                    resetTxt();
                    saveData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            } 
        }else 
            JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);        
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void ttinhCSVCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttinhCSVCMouseClicked
        // TODO add your handling code here:
        dongchon = ttinhCSVC.getSelectedRow();
        if(dongchon !=-1){
            ttinh = dsSCWork.get(dongchon);
            jMaSC.setText(ttinh.getMaSC()+"");
            jMaSC.setEnabled(false);
            jNguoiBT.setText(ttinh.getNguoiBT()+"");
            jDvTinh.setText(ttinh.getDvTinh()+"");
            jMaTS.setText(ttinh.getMaTS()+"");
            jNoiDung.setText(ttinh.getNoiDung()+"");
            jCBKiemTra.setText(ttinh.getCBKiemTra()+"");          
            jNgaySC.setText(ttinh.getNgaySC()+"");          
            jComboTT.setSelectedItem(ttinh.getTrangThai());
            jTextYKien.setText(ttinh.getyKien());
        }
    }//GEN-LAST:event_ttinhCSVCMouseClicked

    private void jButtonXNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXNActionPerformed
        // TODO add your handling code here:
        dongchon = ttinhCSVC.getSelectedRow();
        if(dongchon != -1){                                                                        
                    ttinh = dsTTinh.get(dongchon);
//                    ttinh = dsTaiSanTL.get(dsTaiSanTL.indexOf(tstl));
                    ttinh.setTrangThai(jComboTT.getSelectedItem().toString());
                    ttinh.setyKien(jTextYKien.getText());
                    LoadTableSC(dsTTinh);
                    resetTxt();
                    jComboTT.setSelectedIndex(0);
                    jTextYKien.setText("");
                    saveData();                          
        }else
                JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để xét duyệt!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonXNActionPerformed

    private void jComboTTLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTTLocActionPerformed
        // TODO add your handling code here:
        ArrayList<SuaChua> dsLoc = new ArrayList<>();
        String itemLoc = jComboTTLoc.getSelectedItem().toString();
        if(itemLoc.equalsIgnoreCase("Tất cả")){
            LoadTableSC(dsTTinh);
            dsSCWork=dsTTinh;
        }            
        else{
            for(SuaChua itm : dsTTinh) 
                if(itm.getTrangThai().equalsIgnoreCase(itemLoc)) dsLoc.add(itm);
            LoadTableSC(dsLoc);
            dsSCWork=dsLoc;
        }
    }//GEN-LAST:event_jComboTTLocActionPerformed

    private void jButtonInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInDSActionPerformed
        // TODO add your handling code here:
        ArrayList<SuaChua> dsDuyet = new ArrayList<>();
        for(SuaChua itm : dsTTinh) 
            if(itm.getTrangThai().equalsIgnoreCase("Được duyệt")) dsDuyet.add(itm);
        
        JIn_DSDuyet inDSDForm = new JIn_DSDuyet(dsDuyet);
        inDSDForm.setVisible(true);
    }//GEN-LAST:event_jButtonInDSActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JMSThietBi qlMSForm = new JMSThietBi();
        qlMSForm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JQLTaiSan qlTSForm = new JQLTaiSan();
        qlTSForm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JTLTaiSan qlTLForm = new JTLTaiSan();
        qlTLForm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        DangNhap dnForm = new DangNhap();
        dnForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    
    /**
     * @param args the command line arguments
     */                                                                                                                                                                                                                                             
    public void resetTxt(){
        jMaSC.setText("");
        jNguoiBT.setText("");
        jDvTinh.setText("");
        jMaTS.setText("");       
        jNoiDung.setText("");
        jCBKiemTra.setText("");
        jNgaySC.setText("01/01/2000");
        jComboTT.setSelectedIndex(0);
        jMaSC.setEnabled(true);
        jMaSC.requestFocus();
        jMaTS.setEnabled(true);
        jMaTS.requestFocus();
        dongchon = -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JQLSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JQLSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JQLSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JQLSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JQLSuaChua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInDS;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXN;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JTextField jCBKiemTra;
    private javax.swing.JComboBox<String> jComboTT;
    private javax.swing.JComboBox<String> jComboTTLoc;
    private javax.swing.JTextField jDvTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMaSC;
    private javax.swing.JTextField jMaTS;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField jNgaySC;
    private javax.swing.JTextField jNguoiBT;
    private javax.swing.JTextArea jNoiDung;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextYKien;
    private javax.swing.JTable ttinhCSVC;
    // End of variables declaration//GEN-END:variables
}
