/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DanhSachTaiSan;

import DangNhap.DangNhap;

import MuaSam.JMSThietBi;
import SuaChua.JQLSuaChua;
import ThanhLy.JTLTaiSan;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Minh
 */
public class JQLTaiSan extends javax.swing.JFrame {

    ArrayList<TaiSan> dsTaiSan = new ArrayList<>();
    ArrayList<TaiSan> dsTSWork = new ArrayList<>();
    int dongchon = -1;
    TaiSan tsan = new TaiSan();
    SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy");
    DBEngine db = new DBEngine();
    String fname = "dsTS.dat";
    /**
     * Creates new form JQLTaiSan
     */
    public JQLTaiSan() {
        initComponents();
        myInit();
        setLocationRelativeTo(null);
        setTitle("Quản lý thông tin tài sản");
    }
    public void myInit(){
        //Đọc dữ liệu từ file khi khởi động
        readData();
        LoadTableTS(dsTaiSan);
        dsTSWork=dsTaiSan;
        //Tạo combo danh mục
        String dm[]={"Công trình xây dựng","Xe ô tô","Máy móc, thiết bị","Phần mềm ứng dụng","Khác"};
        jComboDM.setModel(new javax.swing.DefaultComboBoxModel(dm));
        //Tạo combo danh mục để lọc
        jComboDMLoc.setModel(new javax.swing.DefaultComboBoxModel(dm));
        jComboDMLoc.addItem("Tất cả");
        jComboDMLoc.setSelectedItem("Tất cả");
        //Tạo combo khoa
        String khoa[]={"Nhà trường","Cơ khí","Công nghệ ô tô","Công nghệ thông tin",
                       "Điện","Điện tử","Kế toán - Kiểm toán","Du lịch","Ngoại ngữ",
                       "Chính trị - Pháp luật","Công nghệ Hóa học","May"};
        jComboKhoa.setModel(new javax.swing.DefaultComboBoxModel(khoa));                
    }
    public void LoadTableTS(ArrayList<TaiSan> ds){
        tableTS.setModel(new TableTaiSan(ds));
    }
    public void saveData(){        
        try {
            db.LuuFile(fname,dsTaiSan);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi lưu dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void readData(){
        try {
            dsTaiSan = (ArrayList<TaiSan>) db.docFile(fname);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sách hiện tại rỗng!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi đọc dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMaTS = new javax.swing.JTextField();
        labe2 = new javax.swing.JLabel();
        jTenTS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDvTinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTinhTrang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jNgayBH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jGiaTri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSoHuu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMucDich = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboDM = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboKhoa = new javax.swing.JComboBox<>();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboDMLoc = new javax.swing.JComboBox<>();
        jTextTim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonLoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTS = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thực hiện"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã tài sản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, -1));
        jPanel1.add(jMaTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 58, 170, -1));

        labe2.setText("Tên tài sản");
        jPanel1.add(labe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 87, -1, -1));
        jPanel1.add(jTenTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 84, 170, -1));

        jLabel2.setText("Đơn vị tính");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 113, -1, -1));
        jPanel1.add(jDvTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        jLabel3.setText("Tình trạng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 139, -1, -1));
        jPanel1.add(jTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 136, 170, -1));

        jLabel4.setText("Ngày hết bảo hành");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 61, -1, -1));

        jNgayBH.setText("20/5/2023");
        jNgayBH.setToolTipText("Nhập định dạng ngày/tháng/năm");
        jNgayBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNgayBHActionPerformed(evt);
            }
        });
        jPanel1.add(jNgayBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 58, 170, -1));

        jLabel5.setText("Giá trị");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 87, -1, -1));

        jGiaTri.setToolTipText("");
        jGiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGiaTriActionPerformed(evt);
            }
        });
        jPanel1.add(jGiaTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 84, 170, -1));

        jLabel6.setText("Sở hữu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 113, -1, -1));
        jPanel1.add(jSoHuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 110, 170, -1));

        jLabel7.setText("Mục đích sử dụng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 139, -1, -1));
        jPanel1.add(jMucDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 136, 170, -1));

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 70, -1));

        jLabel8.setText("Danh mục");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jComboDM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 27, 170, -1));

        jLabel9.setText("Khoa quản lý");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 30, -1, -1));

        jComboKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 27, 170, -1));

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 70, -1));

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 670, 202));
        jPanel1.getAccessibleContext().setAccessibleName("Chức năng");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lọc"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Danh mục");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jComboDMLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboDMLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDMLocActionPerformed(evt);
            }
        });
        jPanel2.add(jComboDMLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, -1));
        jPanel2.add(jTextTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, -1));

        jLabel11.setText("Từ khóa tìm kiếm");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButtonLoc.setText("Tìm");
        jButtonLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 220, 202));

        tableTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1090, 210));

        jMenu1.setText("Đăng xuất");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Chức năng");

        jMenuItem1.setText("Mua sắm tài sản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Sửa chữa tài sản");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Thanh lý tài sản");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTSMouseClicked
        // TODO add your handling code here:
        dongchon = tableTS.getSelectedRow();
        if(dongchon !=-1){
            tsan = dsTSWork.get(dongchon);
            jMaTS.setText(tsan.getMaTS()+"");
            jMaTS.setEnabled(false);
            jTenTS.setText(tsan.getTenTS()+"");
            jTinhTrang.setText(tsan.getTinhTrang()+"");
            jDvTinh.setText(tsan.getDvTinh()+"");
            jNgayBH.setText(tsan.getNgayBH()+"");
            jGiaTri.setText(tsan.getGiaTri()+"");
            jSoHuu.setText(tsan.getSoHuu()+"");
            jMucDich.setText(tsan.getMucDich()+"");
            jComboDM.setSelectedItem(tsan.getDanhMuc());
            jComboKhoa.setSelectedItem(tsan.getKhoaQl());
        }
    }//GEN-LAST:event_tableTSMouseClicked
    
    
    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        if(jMaTS.getText().trim().length()==0)
                JOptionPane.showMessageDialog(null, "Mã tài sản không được để trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else {
            try {            
                tsan = new TaiSan(jMaTS.getText(),jTenTS.getText(),jDvTinh.getText(),jTinhTrang.getText(),
                                  format.parse(jNgayBH.getText()),jGiaTri.getText(),jSoHuu.getText(),
                                  jMucDich.getText(),jComboDM.getSelectedItem().toString(),jComboKhoa.getSelectedItem().toString());            
                if(dsTaiSan.contains(tsan)) 
                    JOptionPane.showMessageDialog(null, "Đã tồn tại mã tài sản, mời nhập lại!\n","Lỗi", JOptionPane.ERROR_MESSAGE);
                else{
                    dsTaiSan.add(tsan);
                    LoadTableTS(dsTaiSan);                
                    resetTxt();
                    saveData();
                }            
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Hãy kiểm tra dữ liệu, định dạng ngày kiểu MM/dd/yyyy!\n" + ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jGiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGiaTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGiaTriActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        //Lấy vị trí của tài sản trong bảng trên giao diện
        dongchon = tableTS.getSelectedRow();
        if(dongchon != -1){                        
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                try {
                    //JOptionPane.showMessageDialog(null, "Trường mã sẽ không được cập nhật!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    //Lấy tài sản từ danh sách tạm dsTSWork làm việc với bảng
                    tsan = dsTSWork.get(dongchon);
                    //Lấy tài sản từ danh sách gốc để sửa                    
                    tsan = dsTaiSan.get(dsTaiSan.indexOf(tsan));
                    //Thực hiện sửa dữ liệu từ các điều khiển bằng hàm setter
                    tsan.setTenTS(jTenTS.getText());
                    tsan.setTinhTrang(jTinhTrang.getText());
                    tsan.setDvTinh(jDvTinh.getText());
                    tsan.setNgayBH(format.parse(jNgayBH.getText()));
                    tsan.setGiaTri(jGiaTri.getText());
                    tsan.setSoHuu(jSoHuu.getText());
                    tsan.setMucDich(jMucDich.getText());
                    tsan.setDanhMuc(jComboDM.getSelectedItem().toString());
                    tsan.setKhoaQl(jComboKhoa.getSelectedItem().toString());
                    //Hiển thị lại bảng sau khi sửa
                    LoadTableTS(dsTaiSan);
                    //Đặt lại các điều khiển
                    resetTxt();
                    //Lưu dữ liệu vào file
                    saveData();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Hãy kiểm tra dữ liệu, định dạng ngày kiểu MM/dd/yyyy!\n" + ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else
                JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);                
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        dongchon = tableTS.getSelectedRow();
        if (dongchon != -1){            
            tsan = dsTSWork.get(dongchon); 
            tsan = dsTaiSan.get(dsTaiSan.indexOf(tsan));
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                try {
                    dsTaiSan.remove(tsan);
                    LoadTableTS(dsTaiSan);
                    resetTxt();
                    saveData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            } 
        }else 
            JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocActionPerformed
        // TODO add your handling code here:
        ArrayList<TaiSan> dsLoc = new ArrayList<>();
        String itemLoc = jComboDMLoc.getSelectedItem().toString();
        String tuLoc = jTextTim.getText().toLowerCase();
        if(itemLoc.equalsIgnoreCase("Tất cả") && tuLoc.trim().length()==0){
            LoadTableTS(dsTaiSan);
            dsTSWork = dsTaiSan;
        }            
        else if(itemLoc.equalsIgnoreCase("Tất cả") && tuLoc.trim().length()!=0){
            for(TaiSan itm : dsTaiSan) 
                if(itm.getTenTS().toLowerCase().contains(tuLoc)) dsLoc.add(itm);
            LoadTableTS(dsLoc);
            dsTSWork=dsLoc;
        }
        else if(!itemLoc.equalsIgnoreCase("Tất cả") && tuLoc.trim().length()==0){
            for(TaiSan itm : dsTaiSan) 
                if(itm.getDanhMuc().equalsIgnoreCase(itemLoc)) dsLoc.add(itm);
            LoadTableTS(dsLoc);
            dsTSWork=dsLoc;
        }else{
            for(TaiSan itm : dsTaiSan) 
                if(itm.getDanhMuc().equalsIgnoreCase(itemLoc) && itm.getTenTS().toLowerCase().contains(tuLoc)) dsLoc.add(itm);
            LoadTableTS(dsLoc);
            dsTSWork=dsLoc;
        }            
    }//GEN-LAST:event_jButtonLocActionPerformed

    private void jComboDMLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDMLocActionPerformed
        // TODO add your handling code here:
        ArrayList<TaiSan> dsLoc = new ArrayList<>();
        String itemLoc = jComboDMLoc.getSelectedItem().toString();
        if(itemLoc.equalsIgnoreCase("Tất cả")){
            LoadTableTS(dsTaiSan);
            dsTSWork=dsTaiSan;
        }            
        else{
            for(TaiSan itm : dsTaiSan) 
                if(itm.getDanhMuc().equalsIgnoreCase(itemLoc)) dsLoc.add(itm);
            LoadTableTS(dsLoc);
            dsTSWork=dsLoc;
        }
    }//GEN-LAST:event_jComboDMLocActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        DangNhap dnForm = new DangNhap();
        dnForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jNgayBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNgayBHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNgayBHActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JMSThietBi qlMSForm = new JMSThietBi();
        qlMSForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JQLSuaChua qlSCForm = new JQLSuaChua();
        qlSCForm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JTLTaiSan qlTLForm = new JTLTaiSan();
        qlTLForm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    public void resetTxt(){
        jMaTS.setText("");
        jTenTS.setText("");
        jDvTinh.setText("");
        jTinhTrang.setText("");
        jNgayBH.setText("01/01/2000");
        jGiaTri.setText("");
        jSoHuu.setText("");
        jMucDich.setText("");
        jComboDM.setSelectedIndex(0);
        jComboKhoa.setSelectedIndex(0);
        jMaTS.setEnabled(true);
        jMaTS.requestFocus();
        dongchon = -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JQLTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JQLTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JQLTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JQLTaiSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JQLTaiSan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoc;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboDM;
    private javax.swing.JComboBox<String> jComboDMLoc;
    private javax.swing.JComboBox<String> jComboKhoa;
    private javax.swing.JTextField jDvTinh;
    private javax.swing.JTextField jGiaTri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMaTS;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jMucDich;
    private javax.swing.JTextField jNgayBH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSoHuu;
    private javax.swing.JTextField jTenTS;
    private javax.swing.JTextField jTextTim;
    private javax.swing.JTextField jTinhTrang;
    private javax.swing.JLabel labe2;
    private javax.swing.JTable tableTS;
    // End of variables declaration//GEN-END:variables
}
